name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: cd aulas/api-solid

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          dir: ./aulas/api-solid

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: aulas/api-solid/pnpm-lock.yaml

      - run: pnpm install --silent

      - run: pnpm run test
